export { default as Activate } from "./Activate";
export { default as Admin } from "./Admin";
export { default as ForgetPassword } from "./ForgetPassword";
export { default as GoogleAuth } from "./GoogleAuth";
export { default as Login } from "./Login";
export { default as Private } from "./Private";
export { default as Register } from "./Register";
export { default as ResetPassword } from "./ResetPassword";
export { default as GithubAuth } from "./GithubAuth";
